name: on-pull-request
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-artifacts:
    name: Build and Pack Library
    runs-on: ubuntu-latest
    steps:
      - name: install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.10.3'
      - name: setup nuget
        uses: NuGet/setup-nuget@v1.1.1
        with:
          nuget-version: latest
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: create nuget package
        run: bash build.sh --configuration release
        shell: bash
      - name: push nuget package
        run: nuget push artifacts/* -Source https://api.nuget.org/v3/index.json -apikey ${{ secrets.NUGET_API_KEY }}
