name: on-pull-request
on:
  push:
    branches:
      - main
      - dev

jobs:
  build-package:
    name: Build and Pack Library
    runs-on: ubuntu-latest
    steps:
      - name: install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.10.3'
      - name: setup nuget
        uses: NuGet/setup-nuget@v1.1.1
        with:
          nuget-version: latest
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: create nuget package
        run: bash build.sh --configuration release
        shell: bash
      - name: determine version
        id: git_version
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: add git tag
        uses: cardinalby/git-tag-action@v1.0
        env:
          TAG: $ {{ steps.git_version.outputs.nuGetVersionV2 }}
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./artifacts/
          name: artifacts
  push-nuget-packages:
    runs-on: ubuntu-latest
    needs: build-package
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
      - name: push nuget package
        run: nuget push artifacts/* -Source https://api.nuget.org/v3/index.json -apikey ${{ secrets.NUGET_API_KEY }}
